paper_demo:
  target: default
  outputs:
    default:
      type: bigquery
      method: service-account
      project: your-gcp-project-id
      dataset: your_dataset
      timeout_seconds: 300
      threads: 4
      location: US

